stages:
  - test
  - push

variables:
  APPLICATION_NAME: user-manager-mongoose
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

test:
  stage: test
  tags:
    - testing

  script:
    # Run test
    - docker build -t ${DOCKER_IMAGE} .
    - >
      docker run
      --rm
      --name tdd
      -e MONGODB_URL=mongodb://192.168.1.2
      -e MONGODB_DB=user_manager_tdd
      -e JWT_SECRET=keyboardcat
      ${DOCKER_IMAGE}
      npm run coverage


push:
  stage: push
  tags:
    - moreillon
    - "x86"
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
