stages:
  - containerization

variables:
  APPLICATION_NAME: user-manager-mongoose
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}


containerization:
  stage: containerization
  tags:
    - moreillon
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
